### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by sainisanjay** [rakelkar/snpe_convert#1]
Any idea for the below error
```
saini@saini:~/deeplearning/SNPE/snpe-1.29.0.456$ python /home/saini/flawer/show_classifications.py -i /home/saini/flawer/samples.txt -o /home/saini/flawer/flower_output/ -l /home/saini/flawer/labels.txt -s /home/saini/flawer/flower_output/Result_0/detection_classes\:
Classification results
Result_0
/home/saini/flawer/flower_output/Result_0/detection_classes:0.raw
Traceback (most recent call last):
  File "/home/saini/flawer/show_classifications.py", line 92, in <module>
    main()
  File "/home/saini/flawer/show_classifications.py", line 66, in main
    raise RuntimeError(str(len(float_array)) + ' outputs in ' + cur_results_file)
RuntimeError: 100 outputs in /home/saini/flawer/flower_output/Result_0/detection_classes:0.raw
```

**Comment by rakelkar** [comment]
```
if len(float_array) != num_labels:
```
Number of outputs from the model dont match number of labels.

**Comment by sainisanjay** [comment]
@rakelkar Thanks

**Comment by sainisanjay** [comment]
Hi @rakelkar i just want to check with you, can i test .dlc with RGB(.jpeg,png) images instead of .raw images?? 
If you have any idea about that kindly guide me. 
Thanks

**Comment by rakelkar** [comment]
Not directly - but you can use toraw to convert jpg to raw...
